/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FAIPlayer1.java
 *
 * Created on Sep 20, 2009, 10:33:09 AM
 */

package Forms;

import ClassModules.PlayerMat;
import Modules.PlayerMatAccess;
import static Modules.PRGameData.*;
import Modules.SetupPlayerNames;
import static Modules.Constants.*;

/**
 *
 * @author steve
 */
public class FAIPlayer1 extends javax.swing.JDialog {
    private static final long serialVersionUID = 1L;

    /** Creates new form FAIPlayer1 */
    public FAIPlayer1(java.awt.Frame parent, boolean modal, SetupPlayerNames sPlayer) {
        super(parent, modal);
        initComponents();
	{
	int Player = sPlayer.ordinal();
	playermat.iPlayer = Player;
	playermat.form = this;
//	Numbers, doubloons, vps, san juan, barrels
        playermat.Text1[0] = jTextField1;
        playermat.Text1[1] = jTextField2;
        playermat.Text1[2] = jTextField3;
        playermat.Text1[3] = jTextField4;
        playermat.Text1[4] = jTextField5;
        playermat.Text1[5] = jTextField6;
        playermat.Text1[6] = jTextField7;
        playermat.Text1[7] = jTextField8;
        playermat.Text1[8] = jTextField9;
//	Plantations
	playermat.Image2 [0] = jLabel2;
        playermat.Image2 [1] = jLabel3;
        playermat.Image2 [2] = jLabel4;
        playermat.Image2 [3] = jLabel5;
        playermat.Image2 [4] = jLabel6;
        playermat.Image2 [5] = jLabel7;
        playermat.Image2 [6] = jLabel8;
        playermat.Image2 [7] = jLabel9;
        playermat.Image2 [8] = jLabel10;
        playermat.Image2 [9] = jLabel11;
        playermat.Image2 [10] = jLabel12;
        playermat.Image2 [11] = jLabel13;
	for (int i = 1; i <= 11; i++){
		playermat.Image2[i].setVisible(false);
	};
//	Governor Card
        playermat.Image3 = jLabel14;
	jLabel14.setVisible(false);
//	Buildings
        playermat.Image10[0] = jLabel15;
	playermat.Image10lp = jLayeredPane2;
//	Done Button
	playermat.Command1 = jButton1;
	jButton1.setVisible(false);
        
        this.setIconImages(Modules.PRGameData.PRFetchResource.FI(
                new String[] {"icon_16x16","icon_32x32","icon_64x64","icon_128x128"}
        ));	
	}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLayeredPane1 = new javax.swing.JLayeredPane();
                jTextField1 = new javax.swing.JTextField();
                jTextField2 = new javax.swing.JTextField();
                jTextField3 = new javax.swing.JTextField();
                jTextField4 = new javax.swing.JTextField();
                jLayeredPane3 = new javax.swing.JLayeredPane();
                jTextField5 = new javax.swing.JTextField();
                jTextField6 = new javax.swing.JTextField();
                jTextField7 = new javax.swing.JTextField();
                jTextField8 = new javax.swing.JTextField();
                jTextField9 = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                jLabel10 = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                jLabel12 = new javax.swing.JLabel();
                jLabel13 = new javax.swing.JLabel();
                jLabel14 = new javax.swing.JLabel();
                jTextField29 = new javax.swing.JTextField();
                jTextField30 = new javax.swing.JTextField();
                jTextField31 = new javax.swing.JTextField();
                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jLayeredPane2 = new javax.swing.JLayeredPane();
                jLabel15 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jTextField1.setBackground(new java.awt.Color(204, 204, 204));
                jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11));
                jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField1.setText("0");
                jTextField1.setBounds(50, 270, 30, 20);
                jLayeredPane1.add(jTextField1, javax.swing.JLayeredPane.PALETTE_LAYER);

                jTextField2.setBackground(new java.awt.Color(204, 204, 204));
                jTextField2.setEditable(false);
                jTextField2.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField2.setText("0");
                jTextField2.setBounds(30, 360, 40, 40);
                jLayeredPane1.add(jTextField2, javax.swing.JLayeredPane.PALETTE_LAYER);

                jTextField3.setBackground(new java.awt.Color(204, 204, 204));
                jTextField3.setEditable(false);
                jTextField3.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField3.setText("0");
                jTextField3.setBounds(30, 430, 40, 40);
                jLayeredPane1.add(jTextField3, javax.swing.JLayeredPane.PALETTE_LAYER);

                jTextField4.setBackground(new java.awt.Color(204, 204, 204));
                jTextField4.setEditable(false);
                jTextField4.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField4.setText("0");
                jTextField4.setBounds(30, 500, 40, 40);
                jLayeredPane1.add(jTextField4, javax.swing.JLayeredPane.PALETTE_LAYER);

                jTextField5.setBackground(new java.awt.Color(0, 0, 255));
                jTextField5.setEditable(false);
                jTextField5.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField5.setForeground(new java.awt.Color(255, 255, 255));
                jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField5.setText("0");
                jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jTextField5MouseReleased(evt);
                        }
                });
                jTextField5.setBounds(0, 0, 30, 30);
                jLayeredPane3.add(jTextField5, javax.swing.JLayeredPane.PALETTE_LAYER);

                jTextField6.setEditable(false);
                jTextField6.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField6.setForeground(new java.awt.Color(51, 51, 51));
                jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField6.setText("0");
                jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jTextField6MouseReleased(evt);
                        }
                });
                jTextField6.setBounds(60, 0, 30, 30);
                jLayeredPane3.add(jTextField6, javax.swing.JLayeredPane.PALETTE_LAYER);

                jTextField7.setBackground(new java.awt.Color(255, 255, 0));
                jTextField7.setEditable(false);
                jTextField7.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField7.setForeground(new java.awt.Color(51, 51, 51));
                jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField7.setText("0");
                jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jTextField7MouseReleased(evt);
                        }
                });
                jTextField7.setBounds(120, 0, 30, 30);
                jLayeredPane3.add(jTextField7, javax.swing.JLayeredPane.PALETTE_LAYER);

                jTextField8.setBackground(new java.awt.Color(204, 153, 0));
                jTextField8.setEditable(false);
                jTextField8.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField8.setForeground(new java.awt.Color(51, 51, 51));
                jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField8.setText("0");
                jTextField8.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jTextField8MouseReleased(evt);
                        }
                });
                jTextField8.setBounds(180, 0, 30, 30);
                jLayeredPane3.add(jTextField8, javax.swing.JLayeredPane.PALETTE_LAYER);

                jTextField9.setBackground(new java.awt.Color(102, 51, 0));
                jTextField9.setEditable(false);
                jTextField9.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField9.setForeground(new java.awt.Color(255, 255, 255));
                jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField9.setText("0");
                jTextField9.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jTextField9MouseReleased(evt);
                        }
                });
                jTextField9.setBounds(240, 0, 30, 30);
                jLayeredPane3.add(jTextField9, javax.swing.JLayeredPane.PALETTE_LAYER);

                jLayeredPane3.setBounds(140, 240, 270, 30);
                jLayeredPane1.add(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/512.jpg"))); // NOI18N
                jLabel1.setBounds(0, 0, 510, 580);
                jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/10.jpg"))); // NOI18N
                jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel2MouseReleased(evt);
                        }
                });
                jLabel2.setBounds(109, 325, 60, 60);
                jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.PALETTE_LAYER);

                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/10.jpg"))); // NOI18N
                jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel3MouseReleased(evt);
                        }
                });
                jLabel3.setBounds(109, 403, 60, 60);
                jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.PALETTE_LAYER);

                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/10.jpg"))); // NOI18N
                jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel4MouseReleased(evt);
                        }
                });
                jLabel4.setBounds(109, 480, 60, 60);
                jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.PALETTE_LAYER);

                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/10.jpg"))); // NOI18N
                jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel5MouseReleased(evt);
                        }
                });
                jLabel5.setBounds(184, 293, 60, 60);
                jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.PALETTE_LAYER);

                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/10.jpg"))); // NOI18N
                jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel6MouseReleased(evt);
                        }
                });
                jLabel6.setBounds(184, 370, 60, 60);
                jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.PALETTE_LAYER);

                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/10.jpg"))); // NOI18N
                jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel7MouseReleased(evt);
                        }
                });
                jLabel7.setBounds(184, 447, 60, 60);
                jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.PALETTE_LAYER);

                jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/10.jpg"))); // NOI18N
                jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel8MouseReleased(evt);
                        }
                });
                jLabel8.setBounds(260, 317, 60, 60);
                jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.PALETTE_LAYER);

                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/10.jpg"))); // NOI18N
                jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel9MouseReleased(evt);
                        }
                });
                jLabel9.setBounds(260, 393, 60, 60);
                jLayeredPane1.add(jLabel9, javax.swing.JLayeredPane.PALETTE_LAYER);

                jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/10.jpg"))); // NOI18N
                jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel10MouseReleased(evt);
                        }
                });
                jLabel10.setBounds(260, 472, 60, 60);
                jLayeredPane1.add(jLabel10, javax.swing.JLayeredPane.PALETTE_LAYER);

                jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/10.jpg"))); // NOI18N
                jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel11MouseReleased(evt);
                        }
                });
                jLabel11.setBounds(337, 354, 60, 60);
                jLayeredPane1.add(jLabel11, javax.swing.JLayeredPane.PALETTE_LAYER);

                jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/10.jpg"))); // NOI18N
                jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel12MouseReleased(evt);
                        }
                });
                jLabel12.setBounds(337, 431, 60, 60);
                jLayeredPane1.add(jLabel12, javax.swing.JLayeredPane.PALETTE_LAYER);

                jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/10.jpg"))); // NOI18N
                jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel13MouseReleased(evt);
                        }
                });
                jLabel13.setBounds(412, 390, 60, 60);
                jLayeredPane1.add(jLabel13, javax.swing.JLayeredPane.PALETTE_LAYER);

                jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/527.jpg"))); // NOI18N
                jLabel14.setBounds(420, 480, 60, 90);
                jLayeredPane1.add(jLabel14, javax.swing.JLayeredPane.PALETTE_LAYER);

                jTextField29.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.minimizeIconBackground"));
                jTextField29.setEditable(false);
                jTextField29.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
                jTextField29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField29.setText("Doubloons");
                jTextField29.setVerifyInputWhenFocusTarget(false);
                jTextField29.setBounds(15, 400, 70, 20);
                jLayeredPane1.add(jTextField29, javax.swing.JLayeredPane.PALETTE_LAYER);

                jTextField30.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.minimizeIconBackground"));
                jTextField30.setEditable(false);
                jTextField30.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
                jTextField30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField30.setText("VP Chips");
                jTextField30.setVerifyInputWhenFocusTarget(false);
                jTextField30.setBounds(15, 470, 70, 20);
                jLayeredPane1.add(jTextField30, javax.swing.JLayeredPane.PALETTE_LAYER);

                jTextField31.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.minimizeIconBackground"));
                jTextField31.setEditable(false);
                jTextField31.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
                jTextField31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField31.setText("VP Total");
                jTextField31.setVerifyInputWhenFocusTarget(false);
                jTextField31.setBounds(15, 540, 70, 20);
                jLayeredPane1.add(jTextField31, javax.swing.JLayeredPane.PALETTE_LAYER);

                jButton1.setFont(new java.awt.Font("Tahoma", 0, 12));
                jButton1.setText("Done");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });
                jButton1.setBounds(360, 290, 70, 40);
                jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.PALETTE_LAYER);

                jButton2.setText("Close");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });
                jButton2.setBounds(187, 540, 64, 30);
                jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.PALETTE_LAYER);

                jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel15MouseReleased(evt);
                        }
                });
                jLabel15.setBounds(7, 5, 110, 60);
                jLayeredPane2.add(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLayeredPane2.setBounds(22, 28, 465, 200);
                jLayeredPane1.add(jLayeredPane2, javax.swing.JLayeredPane.PALETTE_LAYER);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 524, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 604, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
     PlayerMat.PlantationClick(evt, PlayerMatNImage2Offset); // Twiddle Planation
    }//GEN-LAST:event_jLabel2MouseReleased

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased
     PlayerMat.PlantationClick(evt, PlayerMatNImage2Offset); // Twiddle Planation
    }//GEN-LAST:event_jLabel3MouseReleased

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
     PlayerMat.PlantationClick(evt, PlayerMatNImage2Offset); // Twiddle Planation
    }//GEN-LAST:event_jLabel4MouseReleased

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
     PlayerMat.PlantationClick(evt, PlayerMatNImage2Offset); // Twiddle Planation
    }//GEN-LAST:event_jLabel5MouseReleased

    private void jLabel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseReleased
     PlayerMat.PlantationClick(evt, PlayerMatNImage2Offset); // Twiddle Planation
    }//GEN-LAST:event_jLabel6MouseReleased

    private void jLabel7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseReleased
     PlayerMat.PlantationClick(evt, PlayerMatNImage2Offset); // Twiddle Planation
    }//GEN-LAST:event_jLabel7MouseReleased

    private void jLabel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseReleased
     PlayerMat.PlantationClick(evt, PlayerMatNImage2Offset); // Twiddle Planation
    }//GEN-LAST:event_jLabel8MouseReleased

    private void jLabel9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseReleased
     PlayerMat.PlantationClick(evt, PlayerMatNImage2Offset); // Twiddle Planation
    }//GEN-LAST:event_jLabel9MouseReleased

    private void jLabel10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseReleased
     PlayerMat.PlantationClick(evt, PlayerMatNImage2Offset); // Twiddle Planation
    }//GEN-LAST:event_jLabel10MouseReleased

    private void jLabel11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseReleased
     PlayerMat.PlantationClick(evt, PlayerMatNImage2Offset); // Twiddle Planation
    }//GEN-LAST:event_jLabel11MouseReleased

    private void jLabel12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseReleased
     PlayerMat.PlantationClick(evt, PlayerMatNImage2Offset); // Twiddle Planation
    }//GEN-LAST:event_jLabel12MouseReleased

    private void jLabel13MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseReleased
     PlayerMat.PlantationClick(evt, PlayerMatNImage2Offset); // Twiddle Planation
    }//GEN-LAST:event_jLabel13MouseReleased

    private void jTextField5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseReleased
      PlayerMat.Text1Picked(evt);
    }//GEN-LAST:event_jTextField5MouseReleased

    private void jTextField6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseReleased
      PlayerMat.Text1Picked(evt);
    }//GEN-LAST:event_jTextField6MouseReleased

    private void jTextField7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseReleased
      PlayerMat.Text1Picked(evt);
    }//GEN-LAST:event_jTextField7MouseReleased

    private void jTextField8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8MouseReleased
      PlayerMat.Text1Picked(evt);
    }//GEN-LAST:event_jTextField8MouseReleased

    private void jTextField9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseReleased
      PlayerMat.Text1Picked(evt);
    }//GEN-LAST:event_jTextField9MouseReleased

    private void jLabel15MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseReleased
     PlayerMat.BuildingClick(evt); // Twiddle Building
    }//GEN-LAST:event_jLabel15MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     jButton1.setVisible(false);
     jButton1.setText("Done");
     //PRPuertoRico.playermat.Command2.setText( = "Next"
     //PRPuertoRico.playermat.Command2.setVisible(true);
     PRPuertoRico.GoGoGo();
     // PRPuertoRico.playermat.Zorder;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FAIPlayer1 dialog = new FAIPlayer1(new javax.swing.JFrame(),
			true, SetupPlayerNames.AIPlayerSPN1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JLayeredPane jLayeredPane1;
        private javax.swing.JLayeredPane jLayeredPane2;
        private javax.swing.JLayeredPane jLayeredPane3;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTextField jTextField2;
        private javax.swing.JTextField jTextField29;
        private javax.swing.JTextField jTextField3;
        private javax.swing.JTextField jTextField30;
        private javax.swing.JTextField jTextField31;
        private javax.swing.JTextField jTextField4;
        private javax.swing.JTextField jTextField5;
        private javax.swing.JTextField jTextField6;
        private javax.swing.JTextField jTextField7;
        private javax.swing.JTextField jTextField8;
        private javax.swing.JTextField jTextField9;
        // End of variables declaration//GEN-END:variables
    public PlayerMatAccess playermat = new PlayerMatAccess(9);
}
