/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FBuildings.java
 *
 * Created on Sep 20, 2009, 10:50:48 AM
 */

package Forms;

import ClassModules.Building;
import Modules.BuildingIdx;
import Modules.MsgBox;
import Modules.SetupAvailableRoles;
import static Modules.PRGameData.*;
import static Modules.BuildingIdx.*;

/**
 *
 * @author steve
 */
public class FBuildings extends javax.swing.JDialog {

    /** Creates new form FBuildings */
    public FBuildings(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Image1[0] = jLabel2; Image1[1] = jLabel3; Image1[2] = jLabel4;
        Image1[3] = jLabel5; Image1[4] = jLabel6; Image1[5] = jLabel7;
        Image1[6] = jLabel8; Image1[7] = jLabel9; Image1[8] = jLabel10;
        Image1[9] = jLabel11; Image1[10] = jLabel12; Image1[11] = jLabel13;
        Image1[12] = jLabel14; Image1[13] = jLabel15; Image1[14] = jLabel16;
        Image1[15] = jLabel17; Image1[16] = jLabel18; Image1[17] = jLabel19;
        Image1[18] = jLabel20; Image1[19] = jLabel21; Image1[20] = jLabel22;
        Image1[21] = jLabel23; Image1[22] = jLabel24;
	Command1 = jButton1;
	Command2 = jButton2;
	Command2.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jButton2 = new javax.swing.JButton();
                jLayeredPane1 = new javax.swing.JLayeredPane();
                jButton1 = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                jLabel10 = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                jLabel12 = new javax.swing.JLabel();
                jLabel13 = new javax.swing.JLabel();
                jLabel14 = new javax.swing.JLabel();
                jLabel15 = new javax.swing.JLabel();
                jLabel16 = new javax.swing.JLabel();
                jLabel17 = new javax.swing.JLabel();
                jLabel18 = new javax.swing.JLabel();
                jLabel19 = new javax.swing.JLabel();
                jLabel20 = new javax.swing.JLabel();
                jLabel21 = new javax.swing.JLabel();
                jLabel22 = new javax.swing.JLabel();
                jLabel23 = new javax.swing.JLabel();
                jLabel24 = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setMinimumSize(new java.awt.Dimension(670, 500));
                setResizable(false);
                addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowClosing(java.awt.event.WindowEvent evt) {
                                formWindowClosing(evt);
                        }
                });
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jButton2.setFont(jButton2.getFont());
                jButton2.setText("No Build");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });
                getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 25, -1, -1));

                jLayeredPane1.setOpaque(true);

                jButton1.setFont(new java.awt.Font("Lucida Bright", 0, 11));
                jButton1.setText("OK");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });
                jButton1.setBounds(570, 450, 60, 23);
                jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/110.jpg"))); // NOI18N
                jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel2MouseReleased(evt);
                        }
                });
                jLabel2.setBounds(10, 65, 110, 60);
                jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/120.jpg"))); // NOI18N
                jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel3MouseReleased(evt);
                        }
                });
                jLabel3.setBounds(10, 135, 110, 60);
                jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/130.jpg"))); // NOI18N
                jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel4MouseReleased(evt);
                        }
                });
                jLabel4.setBounds(10, 205, 110, 60);
                jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/140.jpg"))); // NOI18N
                jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel5MouseReleased(evt);
                        }
                });
                jLabel5.setBounds(10, 275, 110, 60);
                jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/150.jpg"))); // NOI18N
                jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel6MouseReleased(evt);
                        }
                });
                jLabel6.setBounds(10, 350, 110, 60);
                jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/160.jpg"))); // NOI18N
                jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel7MouseReleased(evt);
                        }
                });
                jLabel7.setBounds(10, 420, 110, 60);
                jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/210.jpg"))); // NOI18N
                jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel8MouseReleased(evt);
                        }
                });
                jLabel8.setBounds(145, 65, 110, 60);
                jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/220.jpg"))); // NOI18N
                jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel9MouseReleased(evt);
                        }
                });
                jLabel9.setBounds(145, 135, 110, 60);
                jLayeredPane1.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/230.jpg"))); // NOI18N
                jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel10MouseReleased(evt);
                        }
                });
                jLabel10.setBounds(145, 205, 110, 60);
                jLayeredPane1.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/240.jpg"))); // NOI18N
                jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel11MouseReleased(evt);
                        }
                });
                jLabel11.setBounds(145, 275, 110, 60);
                jLayeredPane1.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/250.jpg"))); // NOI18N
                jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel12MouseReleased(evt);
                        }
                });
                jLabel12.setBounds(145, 350, 110, 60);
                jLayeredPane1.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/260.jpg"))); // NOI18N
                jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel13MouseReleased(evt);
                        }
                });
                jLabel13.setBounds(145, 420, 110, 60);
                jLayeredPane1.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/310.jpg"))); // NOI18N
                jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel14MouseReleased(evt);
                        }
                });
                jLabel14.setBounds(283, 65, 110, 60);
                jLayeredPane1.add(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/320.jpg"))); // NOI18N
                jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel15MouseReleased(evt);
                        }
                });
                jLabel15.setBounds(283, 135, 110, 60);
                jLayeredPane1.add(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/330.jpg"))); // NOI18N
                jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel16MouseReleased(evt);
                        }
                });
                jLabel16.setBounds(283, 205, 110, 60);
                jLayeredPane1.add(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/340.jpg"))); // NOI18N
                jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel17MouseReleased(evt);
                        }
                });
                jLabel17.setBounds(283, 275, 110, 60);
                jLayeredPane1.add(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/350.jpg"))); // NOI18N
                jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel18MouseReleased(evt);
                        }
                });
                jLabel18.setBounds(283, 350, 110, 60);
                jLayeredPane1.add(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/360.jpg"))); // NOI18N
                jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel19MouseReleased(evt);
                        }
                });
                jLabel19.setBounds(283, 420, 110, 60);
                jLayeredPane1.add(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/410.jpg"))); // NOI18N
                jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel20MouseReleased(evt);
                        }
                });
                jLabel20.setBounds(418, 60, 110, 140);
                jLayeredPane1.add(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/420.jpg"))); // NOI18N
                jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel21MouseReleased(evt);
                        }
                });
                jLabel21.setBounds(416, 205, 110, 140);
                jLayeredPane1.add(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/430.jpg"))); // NOI18N
                jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel22MouseReleased(evt);
                        }
                });
                jLabel22.setBounds(416, 345, 110, 140);
                jLayeredPane1.add(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/440.jpg"))); // NOI18N
                jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel23MouseReleased(evt);
                        }
                });
                jLabel23.setBounds(545, 128, 110, 140);
                jLayeredPane1.add(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/450.jpg"))); // NOI18N
                jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jLabel24MouseReleased(evt);
                        }
                });
                jLabel24.setBounds(545, 270, 110, 140);
                jLayeredPane1.add(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/511.jpg"))); // NOI18N
                jLabel1.setBounds(0, 0, 670, 500);
                jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

                getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 670, 500));

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
     ImageClick(evt,SmallIndigoPlantIdx );
    }//GEN-LAST:event_jLabel2MouseReleased

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased
     ImageClick(evt, SmallSugarMillIdx);
    }//GEN-LAST:event_jLabel3MouseReleased

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
     ImageClick(evt,SmallMarketIdx );
    }//GEN-LAST:event_jLabel4MouseReleased

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
     ImageClick(evt,HaciendaIdx );
    }//GEN-LAST:event_jLabel5MouseReleased

    private void jLabel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseReleased
     ImageClick(evt,ConstructionHutIdx );
    }//GEN-LAST:event_jLabel6MouseReleased

    private void jLabel7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseReleased
     ImageClick(evt,SmallWarehouseIdx );
    }//GEN-LAST:event_jLabel7MouseReleased

    private void jLabel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseReleased
     ImageClick(evt,IndigoPlantIdx );
    }//GEN-LAST:event_jLabel8MouseReleased

    private void jLabel9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseReleased
     ImageClick(evt,SugarMillIdx );
    }//GEN-LAST:event_jLabel9MouseReleased

    private void jLabel10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseReleased
     ImageClick(evt,HospiceIdx );
    }//GEN-LAST:event_jLabel10MouseReleased

    private void jLabel11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseReleased
     ImageClick(evt,OfficeIdx );
    }//GEN-LAST:event_jLabel11MouseReleased

    private void jLabel12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseReleased
     ImageClick(evt,LargeMarketIdx );
    }//GEN-LAST:event_jLabel12MouseReleased

    private void jLabel13MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseReleased
     ImageClick(evt,LargeWarehouseIdx );
    }//GEN-LAST:event_jLabel13MouseReleased

    private void jLabel14MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseReleased
     ImageClick(evt,TobaccoStorageIdx );
    }//GEN-LAST:event_jLabel14MouseReleased

    private void jLabel15MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseReleased
     ImageClick(evt,CoffeeRoasterIdx );
    }//GEN-LAST:event_jLabel15MouseReleased

    private void jLabel16MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseReleased
     ImageClick(evt,FactoryIdx );
    }//GEN-LAST:event_jLabel16MouseReleased

    private void jLabel17MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseReleased
     ImageClick(evt,UniversityIdx );
    }//GEN-LAST:event_jLabel17MouseReleased

    private void jLabel18MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseReleased
     ImageClick(evt,HarbourIdx );
    }//GEN-LAST:event_jLabel18MouseReleased

    private void jLabel19MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseReleased
     ImageClick(evt,WharfIdx );
    }//GEN-LAST:event_jLabel19MouseReleased

    private void jLabel20MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseReleased
     ImageClick(evt,GuildHallIdx );
    }//GEN-LAST:event_jLabel20MouseReleased

    private void jLabel22MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseReleased
     ImageClick(evt,FortressIdx );
    }//GEN-LAST:event_jLabel22MouseReleased

    private void jLabel23MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseReleased
     ImageClick(evt,CustomsHouseIdx );
    }//GEN-LAST:event_jLabel23MouseReleased

    private void jLabel24MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseReleased
     ImageClick(evt, CityHallIdx);
    }//GEN-LAST:event_jLabel24MouseReleased

    private void jLabel21MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseReleased
     ImageClick(evt,ResidenceIdx );
    }//GEN-LAST:event_jLabel21MouseReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
//     NoBuild();
    }//GEN-LAST:event_formWindowClosing

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     NoBuild();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     this.setVisible(false);
// if ( PRGDCurrentRole = SetupAvailableRoles.BuilderSAR ) {
//  PRPuertoRico.GoGoGo
//  PRPuertoRico.playermat.Command2.setText( = "Next"
//  PRPuertoRico.playermat.Command2.setVisible(true); = true
// };
//PRPuertoRico.playermat.Command2.setVisible(true); = true


    }//GEN-LAST:event_jButton1ActionPerformed

    private void NoBuild() {
    //No build button
     jButton2.setVisible(false);
     this.setVisible(false);
     PRPuertoRico.GoGoGo();
	    
    }
    
    private void ImageClick (java.awt.event.MouseEvent evt, BuildingIdx WhichBuilding) {
//     SetupPlayerNames Player = Utilities.GetPlayerFromJLabel(evt);

// if ( PRGDCurrentRole = SetupAvailableRoles.BuilderSAR ) {
//  if ( PRPuertoRico.playermat.Command2.setVisible(true); ) {
//  if ( PRInformation.setVisible(true); ) {
//   return;
//  };
// else
//  return;
// };

    if ( PRGDCurrentRole == SetupAvailableRoles.BuilderSAR ) {
     Modules.PRGameData.PRBuildingInfo.Populate(PRGDCurrentPlayer, WhichBuilding);
//     PRBuildingInfo.setModalityType(ModalityType.APPLICATION_MODAL);
//     PRBuildingInfo.setVisible(true);
     MsgBox.Inform(PRBuildingInfo.Panel);
     Building.ConfirmCard();
    }
// if ( PRBuilding.Purchase(Index) ) {
//  Command2.setVisible(true); = false
//  Hide
//  PRPuertoRico.playermat.Command2.setText( = "Next"
//  PRPuertoRico.playermat.Command2.setVisible(true); = true
//  PRPuertoRico.GoGoGo

// };
    };

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FBuildings dialog = new FBuildings(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel16;
        private javax.swing.JLabel jLabel17;
        private javax.swing.JLabel jLabel18;
        private javax.swing.JLabel jLabel19;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel20;
        private javax.swing.JLabel jLabel21;
        private javax.swing.JLabel jLabel22;
        private javax.swing.JLabel jLabel23;
        private javax.swing.JLabel jLabel24;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JLayeredPane jLayeredPane1;
        // End of variables declaration//GEN-END:variables
   public javax.swing.JLabel Image1[] = new javax.swing.JLabel [23];
   public javax.swing.JButton Command1;
   public javax.swing.JButton Command2;
}
