/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FGameOver.java
 *
 * Created on Nov 10, 2009, 9:57:39 AM
 */

package Forms;

import Modules.SetupPlayerNames;
import static Modules.Constants.*;

/**
 *
 * @author steve
 */
public class FGameOver extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;

    /** Creates new form FGameOver */
    public FGameOver() {
        initComponents();
    Frame1[0] = jPanel1;
    Frame1[1] = jPanel2;
    Frame1[2] = jPanel3;
    Frame1[3] = jPanel4;
    Frame1[4] = jPanel5;
    PlayerName[0] = jLabel1;
    PlayerName[1] = jLabel10;
    PlayerName[2] = jLabel15;
    PlayerName[3] = jLabel20;
    PlayerName[4] = jLabel25;
    Total[0] = jTextField1;
    Total[1] = jTextField5;
    Total[2] = jTextField9;
    Total[3] = jTextField13;
    Total[4] = jTextField17;
    Chips[0] = jTextField2;
    Chips[1] = jTextField6;
    Chips[2] = jTextField10;
    Chips[3] = jTextField14;
    Chips[4] = jTextField18;
    Buildings[0] = jTextField3;
    Buildings[1] = jTextField7;
    Buildings[2] = jTextField11;
    Buildings[3] = jTextField15;
    Buildings[4] = jTextField19;
    TieBreaker[0] = jTextField4;
    TieBreaker[1] = jTextField8;
    TieBreaker[2] = jTextField12;
    TieBreaker[3] = jTextField16;
    TieBreaker[4] = jTextField20;
    }

   public void setWinnerLabel (SetupPlayerNames Winner){
    int top = EOGWinnerLeft + EOGLeftIncr*Winner.ordinal();
     jTextField24.setLocation(top , EOGWinnerTop);
 };

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jTextField21 = new javax.swing.JTextField();
                jTextField22 = new javax.swing.JTextField();
                jTextField23 = new javax.swing.JTextField();
                jTextArea1 = new javax.swing.JTextArea();
                jTextField1 = new javax.swing.JTextField();
                jTextField2 = new javax.swing.JTextField();
                jTextField3 = new javax.swing.JTextField();
                jTextField4 = new javax.swing.JTextField();
                jPanel2 = new javax.swing.JPanel();
                jLabel10 = new javax.swing.JLabel();
                jTextField25 = new javax.swing.JTextField();
                jTextField26 = new javax.swing.JTextField();
                jTextField27 = new javax.swing.JTextField();
                jTextArea2 = new javax.swing.JTextArea();
                jTextField5 = new javax.swing.JTextField();
                jTextField6 = new javax.swing.JTextField();
                jTextField7 = new javax.swing.JTextField();
                jTextField8 = new javax.swing.JTextField();
                jPanel3 = new javax.swing.JPanel();
                jLabel15 = new javax.swing.JLabel();
                jTextField29 = new javax.swing.JTextField();
                jTextField30 = new javax.swing.JTextField();
                jTextField31 = new javax.swing.JTextField();
                jTextArea3 = new javax.swing.JTextArea();
                jTextField9 = new javax.swing.JTextField();
                jTextField10 = new javax.swing.JTextField();
                jTextField11 = new javax.swing.JTextField();
                jTextField12 = new javax.swing.JTextField();
                jPanel4 = new javax.swing.JPanel();
                jLabel20 = new javax.swing.JLabel();
                jTextField33 = new javax.swing.JTextField();
                jTextField34 = new javax.swing.JTextField();
                jTextField35 = new javax.swing.JTextField();
                jTextArea4 = new javax.swing.JTextArea();
                jTextField13 = new javax.swing.JTextField();
                jTextField14 = new javax.swing.JTextField();
                jTextField15 = new javax.swing.JTextField();
                jTextField16 = new javax.swing.JTextField();
                jPanel5 = new javax.swing.JPanel();
                jLabel25 = new javax.swing.JLabel();
                jTextField37 = new javax.swing.JTextField();
                jTextField38 = new javax.swing.JTextField();
                jTextField39 = new javax.swing.JTextField();
                jTextArea5 = new javax.swing.JTextArea();
                jTextField17 = new javax.swing.JTextField();
                jTextField18 = new javax.swing.JTextField();
                jTextField19 = new javax.swing.JTextField();
                jTextField20 = new javax.swing.JTextField();
                jLabel26 = new javax.swing.JLabel();
                jTextField24 = new javax.swing.JTextField();

                setPreferredSize(new java.awt.Dimension(880, 260));
                setLayout(null);

                jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                jPanel1.setMinimumSize(new java.awt.Dimension(140, 170));
                jPanel1.setName("jPanel1"); // NOI18N
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("Player 1");
                jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
                jLabel1.setName("jLabel1"); // NOI18N
                jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, -1));

                jTextField21.setText("VP Total");
                jTextField21.setBorder(null);
                jTextField21.setName("jTextField21"); // NOI18N
                jTextField21.setOpaque(false);
                jPanel1.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, -1));

                jTextField22.setText("VP Chips");
                jTextField22.setBorder(null);
                jTextField22.setName("jTextField22"); // NOI18N
                jTextField22.setOpaque(false);
                jPanel1.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, -1));

                jTextField23.setText("VP Buildings");
                jTextField23.setBorder(null);
                jTextField23.setName("jTextField23"); // NOI18N
                jTextField23.setOpaque(false);
                jPanel1.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, -1));

                jTextArea1.setColumns(20);
                jTextArea1.setEditable(false);
                jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 11));
                jTextArea1.setLineWrap(true);
                jTextArea1.setRows(5);
                jTextArea1.setText("Goods/ Doubloons");
                jTextArea1.setWrapStyleWord(true);
                jTextArea1.setName("jTextArea1"); // NOI18N
                jTextArea1.setOpaque(false);
                jPanel1.add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 40));

                jTextField1.setEditable(false);
                jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18));
                jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField1.setText("0");
                jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jTextField1.setName("jTextField1"); // NOI18N
                jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 40, 30, -1));

                jTextField2.setEditable(false);
                jTextField2.setFont(new java.awt.Font("Tahoma", 1, 18));
                jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField2.setText("0");
                jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jTextField2.setName("jTextField2"); // NOI18N
                jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 70, 30, -1));

                jTextField3.setEditable(false);
                jTextField3.setFont(new java.awt.Font("Tahoma", 1, 18));
                jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField3.setText("0");
                jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jTextField3.setName("jTextField3"); // NOI18N
                jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 100, 30, -1));

                jTextField4.setEditable(false);
                jTextField4.setFont(new java.awt.Font("Tahoma", 1, 18));
                jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField4.setText("0");
                jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jTextField4.setName("jTextField4"); // NOI18N
                jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 130, 30, -1));

                add(jPanel1);
                jPanel1.setBounds(120, 65, 140, 170);

                jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                jPanel2.setMinimumSize(new java.awt.Dimension(140, 170));
                jPanel2.setName("jPanel2"); // NOI18N
                jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
                jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel10.setText("Player 2");
                jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
                jLabel10.setName("jLabel10"); // NOI18N
                jLabel10.setRequestFocusEnabled(false);
                jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, -1));

                jTextField25.setText("VP Total");
                jTextField25.setBorder(null);
                jTextField25.setName("jTextField25"); // NOI18N
                jTextField25.setOpaque(false);
                jPanel2.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, -1));

                jTextField26.setText("VP Chips");
                jTextField26.setBorder(null);
                jTextField26.setName("jTextField26"); // NOI18N
                jTextField26.setOpaque(false);
                jPanel2.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, -1));

                jTextField27.setText("VP Buildings");
                jTextField27.setBorder(null);
                jTextField27.setName("jTextField27"); // NOI18N
                jTextField27.setOpaque(false);
                jPanel2.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, -1));

                jTextArea2.setColumns(20);
                jTextArea2.setEditable(false);
                jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 11));
                jTextArea2.setLineWrap(true);
                jTextArea2.setRows(5);
                jTextArea2.setText("Goods/ Doubloons");
                jTextArea2.setWrapStyleWord(true);
                jTextArea2.setName("jTextArea2"); // NOI18N
                jTextArea2.setOpaque(false);
                jPanel2.add(jTextArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 40));

                jTextField5.setEditable(false);
                jTextField5.setFont(new java.awt.Font("Tahoma", 1, 18));
                jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField5.setText("0");
                jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jTextField5.setName("jTextField5"); // NOI18N
                jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 40, 30, -1));

                jTextField6.setEditable(false);
                jTextField6.setFont(new java.awt.Font("Tahoma", 1, 18));
                jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField6.setText("0");
                jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jTextField6.setName("jTextField6"); // NOI18N
                jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 70, 30, -1));

                jTextField7.setEditable(false);
                jTextField7.setFont(new java.awt.Font("Tahoma", 1, 18));
                jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField7.setText("0");
                jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jTextField7.setName("jTextField7"); // NOI18N
                jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 100, 30, -1));

                jTextField8.setEditable(false);
                jTextField8.setFont(new java.awt.Font("Tahoma", 1, 18));
                jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField8.setText("0");
                jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jTextField8.setName("jTextField8"); // NOI18N
                jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 130, 30, -1));

                add(jPanel2);
                jPanel2.setBounds(270, 65, 140, 170);

                jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                jPanel3.setName("jPanel3"); // NOI18N
                jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
                jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel15.setText("Player 3");
                jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
                jLabel15.setName("jLabel15"); // NOI18N
                jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, -1));

                jTextField29.setText("VP Total");
                jTextField29.setBorder(null);
                jTextField29.setName("jTextField29"); // NOI18N
                jTextField29.setOpaque(false);
                jPanel3.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, -1));

                jTextField30.setText("VP Chips");
                jTextField30.setBorder(null);
                jTextField30.setName("jTextField30"); // NOI18N
                jTextField30.setOpaque(false);
                jPanel3.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, -1));

                jTextField31.setText("VP Buildings");
                jTextField31.setBorder(null);
                jTextField31.setName("jTextField31"); // NOI18N
                jTextField31.setOpaque(false);
                jPanel3.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, -1));

                jTextArea3.setColumns(20);
                jTextArea3.setEditable(false);
                jTextArea3.setFont(new java.awt.Font("Tahoma", 0, 11));
                jTextArea3.setLineWrap(true);
                jTextArea3.setRows(5);
                jTextArea3.setText("Goods/ Doubloons");
                jTextArea3.setWrapStyleWord(true);
                jTextArea3.setName("jTextArea3"); // NOI18N
                jTextArea3.setOpaque(false);
                jPanel3.add(jTextArea3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 40));

                jTextField9.setEditable(false);
                jTextField9.setFont(new java.awt.Font("Tahoma", 1, 18));
                jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField9.setText("0");
                jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jTextField9.setName("jTextField9"); // NOI18N
                jPanel3.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 40, 30, -1));

                jTextField10.setEditable(false);
                jTextField10.setFont(new java.awt.Font("Tahoma", 1, 18));
                jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField10.setText("0");
                jTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jTextField10.setName("jTextField10"); // NOI18N
                jPanel3.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 70, 30, -1));

                jTextField11.setEditable(false);
                jTextField11.setFont(new java.awt.Font("Tahoma", 1, 18));
                jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField11.setText("0");
                jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jTextField11.setName("jTextField11"); // NOI18N
                jPanel3.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 100, 30, -1));

                jTextField12.setEditable(false);
                jTextField12.setFont(new java.awt.Font("Tahoma", 1, 18));
                jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField12.setText("0");
                jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jTextField12.setName("jTextField12"); // NOI18N
                jPanel3.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 130, 30, -1));

                add(jPanel3);
                jPanel3.setBounds(420, 65, 140, 170);

                jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                jPanel4.setName("jPanel4"); // NOI18N
                jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel20.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
                jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel20.setText("Player 4");
                jLabel20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
                jLabel20.setName("jLabel20"); // NOI18N
                jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, -1));

                jTextField33.setText("VP Total");
                jTextField33.setBorder(null);
                jTextField33.setName("jTextField33"); // NOI18N
                jTextField33.setOpaque(false);
                jPanel4.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, -1));

                jTextField34.setText("VP Chips");
                jTextField34.setBorder(null);
                jTextField34.setName("jTextField34"); // NOI18N
                jTextField34.setOpaque(false);
                jPanel4.add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, -1));

                jTextField35.setText("VP Buildings");
                jTextField35.setBorder(null);
                jTextField35.setName("jTextField35"); // NOI18N
                jTextField35.setOpaque(false);
                jPanel4.add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, -1));

                jTextArea4.setColumns(20);
                jTextArea4.setEditable(false);
                jTextArea4.setFont(new java.awt.Font("Tahoma", 0, 11));
                jTextArea4.setLineWrap(true);
                jTextArea4.setRows(5);
                jTextArea4.setText("Goods/ Doubloons");
                jTextArea4.setWrapStyleWord(true);
                jTextArea4.setName("jTextArea4"); // NOI18N
                jTextArea4.setOpaque(false);
                jPanel4.add(jTextArea4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 40));

                jTextField13.setEditable(false);
                jTextField13.setFont(new java.awt.Font("Tahoma", 1, 18));
                jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField13.setText("0");
                jTextField13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jTextField13.setName("jTextField13"); // NOI18N
                jPanel4.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 40, 30, -1));

                jTextField14.setEditable(false);
                jTextField14.setFont(new java.awt.Font("Tahoma", 1, 18));
                jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField14.setText("0");
                jTextField14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jTextField14.setName("jTextField14"); // NOI18N
                jPanel4.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 70, 30, -1));

                jTextField15.setEditable(false);
                jTextField15.setFont(new java.awt.Font("Tahoma", 1, 18));
                jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField15.setText("0");
                jTextField15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jTextField15.setName("jTextField15"); // NOI18N
                jPanel4.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 100, 30, -1));

                jTextField16.setEditable(false);
                jTextField16.setFont(new java.awt.Font("Tahoma", 1, 18));
                jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField16.setText("0");
                jTextField16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jTextField16.setName("jTextField16"); // NOI18N
                jPanel4.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 130, 30, -1));

                add(jPanel4);
                jPanel4.setBounds(570, 65, 140, 170);

                jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                jPanel5.setName("jPanel5"); // NOI18N
                jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel25.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
                jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel25.setText("Player 5");
                jLabel25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
                jLabel25.setName("jLabel25"); // NOI18N
                jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, -1));

                jTextField37.setText("VP Total");
                jTextField37.setBorder(null);
                jTextField37.setName("jTextField37"); // NOI18N
                jTextField37.setOpaque(false);
                jPanel5.add(jTextField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, -1));

                jTextField38.setText("VP Chips");
                jTextField38.setBorder(null);
                jTextField38.setName("jTextField38"); // NOI18N
                jTextField38.setOpaque(false);
                jPanel5.add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, -1));

                jTextField39.setText("VP Buildings");
                jTextField39.setBorder(null);
                jTextField39.setName("jTextField39"); // NOI18N
                jTextField39.setOpaque(false);
                jPanel5.add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, -1));

                jTextArea5.setColumns(20);
                jTextArea5.setEditable(false);
                jTextArea5.setFont(new java.awt.Font("Tahoma", 0, 11));
                jTextArea5.setLineWrap(true);
                jTextArea5.setRows(5);
                jTextArea5.setText("Goods/ Doubloons");
                jTextArea5.setWrapStyleWord(true);
                jTextArea5.setName("jTextArea5"); // NOI18N
                jTextArea5.setOpaque(false);
                jPanel5.add(jTextArea5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 40));

                jTextField17.setEditable(false);
                jTextField17.setFont(new java.awt.Font("Tahoma", 1, 18));
                jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField17.setText("0");
                jTextField17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jTextField17.setName("jTextField17"); // NOI18N
                jPanel5.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 40, 30, -1));

                jTextField18.setEditable(false);
                jTextField18.setFont(new java.awt.Font("Tahoma", 1, 18));
                jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField18.setText("0");
                jTextField18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jTextField18.setName("jTextField18"); // NOI18N
                jPanel5.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 70, 30, -1));

                jTextField19.setEditable(false);
                jTextField19.setFont(new java.awt.Font("Tahoma", 1, 18));
                jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField19.setText("0");
                jTextField19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jTextField19.setName("jTextField19"); // NOI18N
                jPanel5.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 100, 30, -1));

                jTextField20.setEditable(false);
                jTextField20.setFont(new java.awt.Font("Tahoma", 1, 18));
                jTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField20.setText("0");
                jTextField20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jTextField20.setName("jTextField20"); // NOI18N
                jPanel5.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 130, 30, -1));

                add(jPanel5);
                jPanel5.setBounds(720, 65, 140, 170);

                jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12));
                jLabel26.setText("TIE BREAKER");
                jLabel26.setName("jLabel26"); // NOI18N
                add(jLabel26);
                jLabel26.setBounds(20, 205, 73, 15);

                jTextField24.setEditable(false);
                jTextField24.setText("WINNER");
                jTextField24.setName("jTextField24"); // NOI18N
                jTextField24.setOpaque(false);
                jTextField24.setVerifyInputWhenFocusTarget(false);
                add(jTextField24);
                jTextField24.setBounds(170, 40, 55, 20);
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel20;
        private javax.swing.JLabel jLabel25;
        private javax.swing.JLabel jLabel26;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JTextArea jTextArea1;
        private javax.swing.JTextArea jTextArea2;
        private javax.swing.JTextArea jTextArea3;
        private javax.swing.JTextArea jTextArea4;
        private javax.swing.JTextArea jTextArea5;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTextField jTextField10;
        private javax.swing.JTextField jTextField11;
        private javax.swing.JTextField jTextField12;
        private javax.swing.JTextField jTextField13;
        private javax.swing.JTextField jTextField14;
        private javax.swing.JTextField jTextField15;
        private javax.swing.JTextField jTextField16;
        private javax.swing.JTextField jTextField17;
        private javax.swing.JTextField jTextField18;
        private javax.swing.JTextField jTextField19;
        private javax.swing.JTextField jTextField2;
        private javax.swing.JTextField jTextField20;
        private javax.swing.JTextField jTextField21;
        private javax.swing.JTextField jTextField22;
        private javax.swing.JTextField jTextField23;
        private javax.swing.JTextField jTextField24;
        private javax.swing.JTextField jTextField25;
        private javax.swing.JTextField jTextField26;
        private javax.swing.JTextField jTextField27;
        private javax.swing.JTextField jTextField29;
        private javax.swing.JTextField jTextField3;
        private javax.swing.JTextField jTextField30;
        private javax.swing.JTextField jTextField31;
        private javax.swing.JTextField jTextField33;
        private javax.swing.JTextField jTextField34;
        private javax.swing.JTextField jTextField35;
        private javax.swing.JTextField jTextField37;
        private javax.swing.JTextField jTextField38;
        private javax.swing.JTextField jTextField39;
        private javax.swing.JTextField jTextField4;
        private javax.swing.JTextField jTextField5;
        private javax.swing.JTextField jTextField6;
        private javax.swing.JTextField jTextField7;
        private javax.swing.JTextField jTextField8;
        private javax.swing.JTextField jTextField9;
        // End of variables declaration//GEN-END:variables
    public javax.swing.JPanel Frame1[] = new javax.swing.JPanel[5];
    public javax.swing.JLabel PlayerName[] = new javax.swing.JLabel[5];
    public javax.swing.JTextField Total[] = new javax.swing.JTextField[5];
    public javax.swing.JTextField Chips[] = new javax.swing.JTextField[5];
    public javax.swing.JTextField Buildings[] = new javax.swing.JTextField[5];
    public javax.swing.JTextField TieBreaker[] = new javax.swing.JTextField[5];
}
