/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FInformation.java
 *
 * Created on Sep 20, 2009, 10:28:05 AM
 */

package Forms;

import Modules.ImageIdx;

/**
 *
 * @author steve
 */
public class FInformation extends javax.swing.JDialog {
//private boolean PRBuildingSelected = false;
//private TilePickIdx PRTileSelected = TilePickIdx.NullTPI;
//private InfoCardState InfoCS = InfoCardState.inActiveICS;

    /** Creates new form FInformation */
//    public FInformation(java.awt.Frame parent) {
    public FInformation(java.awt.Frame parent, boolean modal) {
//        super(parent, modal);
        super(parent);
        initComponents();
	Panel = jPanel1;
        Image1 = jLabel1;
        Label1 = jTextArea1;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jTextArea1 = new javax.swing.JTextArea();
                jLabel1 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setAlwaysOnTop(true);
                setMinimumSize(new java.awt.Dimension(400, 301));
                setResizable(false);
                addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowClosing(java.awt.event.WindowEvent evt) {
                                formWindowClosing(evt);
                        }
                });
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jTextArea1.setColumns(20);
                jTextArea1.setEditable(false);
                jTextArea1.setFont(new java.awt.Font("Comic Sans MS", 0, 13));
                jTextArea1.setLineWrap(true);
                jTextArea1.setRows(5);
                jTextArea1.setWrapStyleWord(true);
                jTextArea1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                jTextArea1.setOpaque(false);
                jPanel1.add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 240, 160));
                jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, 130));

                getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
     CloseForm();
    }//GEN-LAST:event_formWindowClosing

private void CloseForm (){
 this.setVisible(false);
}

void Initialise() {
// PRBuildingSelected = false;
// PRTileSelected = TilePickIdx.NullTPI;
 this.Image1.setName(ImageIdx.Blank1.SImgIndex());
// InfoCS = InfoCardState.inActiveICS;
};
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FInformation dialog = new FInformation(new javax.swing.JFrame(), false);
//                FInformation dialog = new FInformation(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JTextArea jTextArea1;
        // End of variables declaration//GEN-END:variables
 public javax.swing.JPanel Panel;
 public javax.swing.JLabel Image1;
 public javax.swing.JTextArea Label1;
// public javax.swing.JButton CommandButton1; // OK button
// public javax.swing.JButton CommandButton2; // Yes button
// public javax.swing.JButton CommandButton3; // No button
}
