/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FProductionGrid.java
 *
 * Created on Nov 10, 2009, 9:30:01 AM
 */

package Forms;

import Modules.Constants;

/**
 *
 * @author steve
 */
public class FProductionGrid extends javax.swing.JPanel {

    /** Creates new form FProductionGrid */
    public FProductionGrid() {
        initComponents();
     Panel = this;
     jpanels[0] = jPanel1;
     jpanels[1] = jPanel2;
     jpanels[2] = jPanel3;
     jpanels[3] = jPanel4;
     jpanels[4] = jPanel5;
    }
   public void setCraftsmanLabel (int OnSeat){
    int top = (Constants.GPGridGoodTopIncr * OnSeat) + Constants.GPGridCraftsmanOriginTop;
     jTextField2.setLocation( Constants.GPGridCraftsmanOriginLeft, top);
 };

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jTextField5 = new javax.swing.JTextField();
                jTextField8 = new javax.swing.JTextField();
                jTextField9 = new javax.swing.JTextField();
                jTextField11 = new javax.swing.JTextField();
                jTextField10 = new javax.swing.JTextField();
                jPanel2 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                jTextField6 = new javax.swing.JTextField();
                jTextField12 = new javax.swing.JTextField();
                jTextField13 = new javax.swing.JTextField();
                jTextField14 = new javax.swing.JTextField();
                jTextField15 = new javax.swing.JTextField();
                jPanel3 = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                jTextField7 = new javax.swing.JTextField();
                jTextField16 = new javax.swing.JTextField();
                jTextField17 = new javax.swing.JTextField();
                jTextField18 = new javax.swing.JTextField();
                jTextField19 = new javax.swing.JTextField();
                jPanel4 = new javax.swing.JPanel();
                jLabel5 = new javax.swing.JLabel();
                jTextField20 = new javax.swing.JTextField();
                jTextField21 = new javax.swing.JTextField();
                jTextField22 = new javax.swing.JTextField();
                jTextField23 = new javax.swing.JTextField();
                jTextField24 = new javax.swing.JTextField();
                jPanel5 = new javax.swing.JPanel();
                jLabel6 = new javax.swing.JLabel();
                jTextField25 = new javax.swing.JTextField();
                jTextField26 = new javax.swing.JTextField();
                jTextField27 = new javax.swing.JTextField();
                jTextField28 = new javax.swing.JTextField();
                jTextField29 = new javax.swing.JTextField();
                jTextField1 = new javax.swing.JTextField();
                jTextField2 = new javax.swing.JTextField();

                setPreferredSize(new java.awt.Dimension(480, 480));
                setLayout(null);

                jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                jPanel1.setName("jPanel1"); // NOI18N
                jPanel1.setPreferredSize(new java.awt.Dimension(350, 70));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18));
                jLabel1.setText("Player1");
                jLabel1.setName("jLabel1"); // NOI18N
                jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

                jTextField5.setBackground(new java.awt.Color(0, 0, 255));
                jTextField5.setEditable(false);
                jTextField5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
                jTextField5.setForeground(new java.awt.Color(255, 255, 255));
                jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField5.setText("0");
                jTextField5.setName("jTextField5"); // NOI18N
                jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 40, -1));

                jTextField8.setBackground(new java.awt.Color(254, 255, 255));
                jTextField8.setEditable(false);
                jTextField8.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField8.setForeground(new java.awt.Color(51, 51, 51));
                jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField8.setText("0");
                jTextField8.setName("jTextField8"); // NOI18N
                jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 40, -1));

                jTextField9.setBackground(new java.awt.Color(255, 255, 0));
                jTextField9.setEditable(false);
                jTextField9.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField9.setForeground(new java.awt.Color(51, 51, 51));
                jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField9.setText("0");
                jTextField9.setName("jTextField9"); // NOI18N
                jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 40, -1));

                jTextField11.setBackground(new java.awt.Color(204, 153, 0));
                jTextField11.setEditable(false);
                jTextField11.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField11.setForeground(new java.awt.Color(51, 51, 51));
                jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField11.setText("0");
                jTextField11.setName("jTextField11"); // NOI18N
                jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 40, -1));

                jTextField10.setBackground(new java.awt.Color(102, 51, 0));
                jTextField10.setEditable(false);
                jTextField10.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField10.setForeground(new java.awt.Color(255, 255, 255));
                jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField10.setText("0");
                jTextField10.setName("jTextField10"); // NOI18N
                jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 40, -1));

                add(jPanel1);
                jPanel1.setBounds(120, 50, 350, 70);

                jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                jPanel2.setName("jPanel2"); // NOI18N
                jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18));
                jLabel3.setText("Player2");
                jLabel3.setName("jLabel3"); // NOI18N
                jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

                jTextField6.setBackground(new java.awt.Color(0, 0, 255));
                jTextField6.setEditable(false);
                jTextField6.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField6.setForeground(new java.awt.Color(255, 255, 255));
                jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField6.setText("0");
                jTextField6.setName("jTextField6"); // NOI18N
                jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 40, -1));

                jTextField12.setBackground(new java.awt.Color(254, 255, 255));
                jTextField12.setEditable(false);
                jTextField12.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField12.setForeground(new java.awt.Color(51, 51, 51));
                jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField12.setText("0");
                jTextField12.setName("jTextField12"); // NOI18N
                jPanel2.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 40, -1));

                jTextField13.setBackground(new java.awt.Color(255, 255, 0));
                jTextField13.setEditable(false);
                jTextField13.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField13.setForeground(new java.awt.Color(51, 51, 51));
                jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField13.setText("0");
                jTextField13.setName("jTextField13"); // NOI18N
                jPanel2.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 40, -1));

                jTextField14.setBackground(new java.awt.Color(204, 153, 0));
                jTextField14.setEditable(false);
                jTextField14.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField14.setForeground(new java.awt.Color(51, 51, 51));
                jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField14.setText("0");
                jTextField14.setName("jTextField14"); // NOI18N
                jPanel2.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 40, -1));

                jTextField15.setBackground(new java.awt.Color(102, 51, 0));
                jTextField15.setEditable(false);
                jTextField15.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField15.setForeground(new java.awt.Color(255, 255, 255));
                jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField15.setText("0");
                jTextField15.setName("jTextField15"); // NOI18N
                jPanel2.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 40, -1));

                add(jPanel2);
                jPanel2.setBounds(120, 130, 350, 70);

                jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                jPanel3.setName("jPanel3"); // NOI18N
                jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
                jLabel4.setText("Player3");
                jLabel4.setName("jLabel4"); // NOI18N
                jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

                jTextField7.setBackground(new java.awt.Color(0, 0, 255));
                jTextField7.setEditable(false);
                jTextField7.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField7.setForeground(new java.awt.Color(255, 255, 255));
                jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField7.setText("0");
                jTextField7.setName("jTextField7"); // NOI18N
                jPanel3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 40, -1));

                jTextField16.setBackground(new java.awt.Color(254, 255, 255));
                jTextField16.setEditable(false);
                jTextField16.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField16.setForeground(new java.awt.Color(51, 51, 51));
                jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField16.setText("0");
                jTextField16.setName("jTextField16"); // NOI18N
                jPanel3.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 40, -1));

                jTextField17.setBackground(new java.awt.Color(255, 255, 0));
                jTextField17.setEditable(false);
                jTextField17.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField17.setForeground(new java.awt.Color(51, 51, 51));
                jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField17.setText("0");
                jTextField17.setName("jTextField17"); // NOI18N
                jPanel3.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 40, -1));

                jTextField18.setBackground(new java.awt.Color(204, 153, 0));
                jTextField18.setEditable(false);
                jTextField18.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField18.setForeground(new java.awt.Color(51, 51, 51));
                jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField18.setText("0");
                jTextField18.setName("jTextField18"); // NOI18N
                jPanel3.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 40, -1));

                jTextField19.setBackground(new java.awt.Color(102, 51, 0));
                jTextField19.setEditable(false);
                jTextField19.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField19.setForeground(new java.awt.Color(255, 255, 255));
                jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField19.setText("0");
                jTextField19.setName("jTextField19"); // NOI18N
                jPanel3.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 40, -1));

                add(jPanel3);
                jPanel3.setBounds(120, 210, 350, 70);

                jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                jPanel4.setName("jPanel4"); // NOI18N
                jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 18));
                jLabel5.setText("Player4");
                jLabel5.setName("jLabel5"); // NOI18N
                jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

                jTextField20.setBackground(new java.awt.Color(0, 0, 255));
                jTextField20.setEditable(false);
                jTextField20.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField20.setForeground(new java.awt.Color(255, 255, 255));
                jTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField20.setText("0");
                jTextField20.setName("jTextField20"); // NOI18N
                jPanel4.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 40, -1));

                jTextField21.setBackground(new java.awt.Color(254, 255, 255));
                jTextField21.setEditable(false);
                jTextField21.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField21.setForeground(new java.awt.Color(51, 51, 51));
                jTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField21.setText("0");
                jTextField21.setName("jTextField21"); // NOI18N
                jPanel4.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 40, -1));

                jTextField22.setBackground(new java.awt.Color(255, 255, 0));
                jTextField22.setEditable(false);
                jTextField22.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField22.setForeground(new java.awt.Color(51, 51, 51));
                jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField22.setText("0");
                jTextField22.setName("jTextField22"); // NOI18N
                jPanel4.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 40, -1));

                jTextField23.setBackground(new java.awt.Color(204, 153, 0));
                jTextField23.setEditable(false);
                jTextField23.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField23.setForeground(new java.awt.Color(51, 51, 51));
                jTextField23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField23.setText("0");
                jTextField23.setName("jTextField23"); // NOI18N
                jPanel4.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 40, -1));

                jTextField24.setBackground(new java.awt.Color(102, 51, 0));
                jTextField24.setEditable(false);
                jTextField24.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField24.setForeground(new java.awt.Color(255, 255, 255));
                jTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField24.setText("0");
                jTextField24.setName("jTextField24"); // NOI18N
                jPanel4.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 40, -1));

                add(jPanel4);
                jPanel4.setBounds(120, 290, 350, 70);

                jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                jPanel5.setName("jPanel5"); // NOI18N
                jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 18));
                jLabel6.setText("Player5");
                jLabel6.setName("jLabel6"); // NOI18N
                jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

                jTextField25.setBackground(new java.awt.Color(0, 0, 255));
                jTextField25.setEditable(false);
                jTextField25.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField25.setForeground(new java.awt.Color(255, 255, 255));
                jTextField25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField25.setText("0");
                jTextField25.setName("jTextField25"); // NOI18N
                jPanel5.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 40, -1));

                jTextField26.setBackground(new java.awt.Color(254, 255, 255));
                jTextField26.setEditable(false);
                jTextField26.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField26.setForeground(new java.awt.Color(51, 51, 51));
                jTextField26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField26.setText("0");
                jTextField26.setName("jTextField26"); // NOI18N
                jPanel5.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 40, -1));

                jTextField27.setBackground(new java.awt.Color(255, 255, 0));
                jTextField27.setEditable(false);
                jTextField27.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField27.setForeground(new java.awt.Color(51, 51, 51));
                jTextField27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField27.setText("0");
                jTextField27.setName("jTextField27"); // NOI18N
                jPanel5.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 40, -1));

                jTextField28.setBackground(new java.awt.Color(204, 153, 0));
                jTextField28.setEditable(false);
                jTextField28.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField28.setForeground(new java.awt.Color(51, 51, 51));
                jTextField28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField28.setText("0");
                jTextField28.setName("jTextField28"); // NOI18N
                jPanel5.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 40, -1));

                jTextField29.setBackground(new java.awt.Color(102, 51, 0));
                jTextField29.setEditable(false);
                jTextField29.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField29.setForeground(new java.awt.Color(255, 255, 255));
                jTextField29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField29.setText("0");
                jTextField29.setName("jTextField29"); // NOI18N
                jPanel5.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 40, -1));

                add(jPanel5);
                jPanel5.setBounds(120, 370, 350, 70);

                jTextField1.setEditable(false);
                jTextField1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
                jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField1.setText("Goods Produced this Turn");
                jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                jTextField1.setName("jTextField1"); // NOI18N
                add(jTextField1);
                jTextField1.setBounds(180, 10, 215, 30);

                jTextField2.setEditable(false);
                jTextField2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
                jTextField2.setText("Craftsman");
                jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                jTextField2.setName("jTextField2"); // NOI18N
                jTextField2.setOpaque(false);
                add(jTextField2);
                jTextField2.setBounds(20, 70, 91, 30);
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTextField jTextField10;
        private javax.swing.JTextField jTextField11;
        private javax.swing.JTextField jTextField12;
        private javax.swing.JTextField jTextField13;
        private javax.swing.JTextField jTextField14;
        private javax.swing.JTextField jTextField15;
        private javax.swing.JTextField jTextField16;
        private javax.swing.JTextField jTextField17;
        private javax.swing.JTextField jTextField18;
        private javax.swing.JTextField jTextField19;
        private javax.swing.JTextField jTextField2;
        private javax.swing.JTextField jTextField20;
        private javax.swing.JTextField jTextField21;
        private javax.swing.JTextField jTextField22;
        private javax.swing.JTextField jTextField23;
        private javax.swing.JTextField jTextField24;
        private javax.swing.JTextField jTextField25;
        private javax.swing.JTextField jTextField26;
        private javax.swing.JTextField jTextField27;
        private javax.swing.JTextField jTextField28;
        private javax.swing.JTextField jTextField29;
        private javax.swing.JTextField jTextField5;
        private javax.swing.JTextField jTextField6;
        private javax.swing.JTextField jTextField7;
        private javax.swing.JTextField jTextField8;
        private javax.swing.JTextField jTextField9;
        // End of variables declaration//GEN-END:variables

    public javax.swing.JPanel jpanels[] = new javax.swing.JPanel[Constants.MaxPlayers];
    public javax.swing.JPanel Panel;

}
