/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FSetup.java
 *
 * Created on Sep 18, 2009, 1:33:44 PM
 */

package Forms;

import Modules.SetupChoiceSeat;
import Modules.Utilities;
import static Modules.PRGameData.*;
import static Modules.Constants.*;
import static Modules.SetupChoiceSeat.*;
import static Modules.SetupPlayerNames.*;
import static Modules.SetupNumPlayers.*;

/**
 *
 * @author steve
 */
public class FSetup extends javax.swing.JDialog {

    /** Creates new form FSetup */
    public FSetup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
	AIPlayer [0] = null;
	AIPlayer [1] = jCheckBox1;
	AIPlayer [2] = jCheckBox2;
	AIPlayer [3] = jCheckBox3;
	AIPlayer [4] = jCheckBox4;
        PlayerName [0] = jTextField1;
        PlayerName [1] = jTextField2;
        PlayerName [2] = jTextField3;
        PlayerName [3] = jTextField4;
        PlayerName [4] = jTextField5;
        Option2[0] = jRadioButton5;
        Option2[1] = jRadioButton6;
        Option2[2] = jRadioButton7;
        Option2[3] = jRadioButton8;
        Option2[4] = jRadioButton9;
        Option2[5] = jRadioButton10;
	Label3[0] = jTextField11;
	Label3[1] = jTextField12;
	Label3[2] = jTextField13;
	Label3[3] = jTextField15;
	Label3[4] = jTextField14;
	jTextField15.setVisible(false);
	jTextField14.setVisible(false);
	jTextField4.setVisible(false);
	jTextField5.setVisible(false);
	jCheckBox3.setVisible(false);
	jCheckBox4.setVisible(false);
	jRadioButton8.setVisible(false);
	jRadioButton9.setVisible(false);
	jLabel7.setVisible(false);
	jLabel8.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                buttonGroup1 = new javax.swing.ButtonGroup();
                buttonGroup2 = new javax.swing.ButtonGroup();
                FNumberofPlayers = new javax.swing.JPanel();
                jRadioButton1 = new javax.swing.JRadioButton();
                jRadioButton2 = new javax.swing.JRadioButton();
                jRadioButton3 = new javax.swing.JRadioButton();
                jRadioButton4 = new javax.swing.JRadioButton();
                jTextField6 = new javax.swing.JTextField();
                FChoiceofSeat = new javax.swing.JPanel();
                jRadioButton5 = new javax.swing.JRadioButton();
                jRadioButton6 = new javax.swing.JRadioButton();
                jRadioButton7 = new javax.swing.JRadioButton();
                jRadioButton8 = new javax.swing.JRadioButton();
                jRadioButton9 = new javax.swing.JRadioButton();
                jRadioButton10 = new javax.swing.JRadioButton();
                jTextField8 = new javax.swing.JTextField();
                FAvailableRoles = new javax.swing.JPanel();
                jTextField9 = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                FPlayerNames = new javax.swing.JPanel();
                jTextField10 = new javax.swing.JTextField();
                jTextField11 = new javax.swing.JTextField();
                jTextField12 = new javax.swing.JTextField();
                jTextField13 = new javax.swing.JTextField();
                jTextField15 = new javax.swing.JTextField();
                jTextField14 = new javax.swing.JTextField();
                jTextField16 = new javax.swing.JTextField();
                jTextField1 = new javax.swing.JTextField();
                jTextField2 = new javax.swing.JTextField();
                jTextField3 = new javax.swing.JTextField();
                jTextField4 = new javax.swing.JTextField();
                jTextField5 = new javax.swing.JTextField();
                jCheckBox1 = new javax.swing.JCheckBox();
                jCheckBox2 = new javax.swing.JCheckBox();
                jCheckBox3 = new javax.swing.JCheckBox();
                jCheckBox4 = new javax.swing.JCheckBox();
                jButton1 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setMinimumSize(new java.awt.Dimension(367, 418));
                addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowClosing(java.awt.event.WindowEvent evt) {
                                formWindowClosing(evt);
                        }
                });
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                FNumberofPlayers.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                FNumberofPlayers.setFont(new java.awt.Font("Comic Sans MS", 0, 10));
                FNumberofPlayers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                buttonGroup1.add(jRadioButton1);
                jRadioButton1.setSelected(true);
                jRadioButton1.setText("3 Players");
                jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton1MouseReleased(evt);
                        }
                });
                FNumberofPlayers.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

                buttonGroup1.add(jRadioButton2);
                jRadioButton2.setText("4 Players");
                jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton2MouseReleased(evt);
                        }
                });
                FNumberofPlayers.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, -1, 20));

                buttonGroup1.add(jRadioButton3);
                jRadioButton3.setText("5 Players");
                jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton3MouseReleased(evt);
                        }
                });
                FNumberofPlayers.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

                buttonGroup1.add(jRadioButton4);
                jRadioButton4.setText("Random");
                jRadioButton4.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton4MouseReleased(evt);
                        }
                });
                FNumberofPlayers.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

                jTextField6.setEditable(false);
                jTextField6.setFont(new java.awt.Font("Tahoma", 1, 11));
                jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField6.setText("Number of Players");
                jTextField6.setBorder(null);
                FNumberofPlayers.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 110, -1));

                getContentPane().add(FNumberofPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 40, 120, 110));

                FChoiceofSeat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                FChoiceofSeat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                buttonGroup2.add(jRadioButton5);
                jRadioButton5.setSelected(true);
                jRadioButton5.setText("1st");
                jRadioButton5.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton5MouseReleased(evt);
                        }
                });
                FChoiceofSeat.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

                buttonGroup2.add(jRadioButton6);
                jRadioButton6.setText("2nd");
                jRadioButton6.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton6MouseReleased(evt);
                        }
                });
                FChoiceofSeat.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

                buttonGroup2.add(jRadioButton7);
                jRadioButton7.setText("3rd");
                jRadioButton7.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton7MouseReleased(evt);
                        }
                });
                FChoiceofSeat.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

                buttonGroup2.add(jRadioButton8);
                jRadioButton8.setText("4th");
                jRadioButton8.setOpaque(false);
                jRadioButton8.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton8MouseReleased(evt);
                        }
                });
                FChoiceofSeat.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

                buttonGroup2.add(jRadioButton9);
                jRadioButton9.setText("5th");
                jRadioButton9.setOpaque(false);
                jRadioButton9.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton9MouseReleased(evt);
                        }
                });
                FChoiceofSeat.add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

                buttonGroup2.add(jRadioButton10);
                jRadioButton10.setText("Random");
                jRadioButton10.setRequestFocusEnabled(false);
                jRadioButton10.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton10MouseReleased(evt);
                        }
                });
                FChoiceofSeat.add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

                jTextField8.setEditable(false);
                jTextField8.setFont(new java.awt.Font("Tahoma", 1, 11));
                jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField8.setText("Choice of Seat");
                jTextField8.setBorder(null);
                FChoiceofSeat.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 85, -1));

                getContentPane().add(FChoiceofSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 30, 95, 150));

                FAvailableRoles.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                FAvailableRoles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jTextField9.setEditable(false);
                jTextField9.setFont(new java.awt.Font("Tahoma", 1, 11));
                jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField9.setText("Available Roles");
                jTextField9.setBorder(null);
                FAvailableRoles.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 110, -1));

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/520.jpg"))); // NOI18N
                jLabel1.setRequestFocusEnabled(false);
                FAvailableRoles.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/521.jpg"))); // NOI18N
                jLabel2.setRequestFocusEnabled(false);
                FAvailableRoles.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 90));

                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/522.jpg"))); // NOI18N
                jLabel3.setRequestFocusEnabled(false);
                FAvailableRoles.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/523.jpg"))); // NOI18N
                jLabel4.setRequestFocusEnabled(false);
                FAvailableRoles.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/524.jpg"))); // NOI18N
                jLabel5.setRequestFocusEnabled(false);
                FAvailableRoles.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/525.jpg"))); // NOI18N
                jLabel6.setRequestFocusEnabled(false);
                FAvailableRoles.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/526.jpg"))); // NOI18N
                jLabel7.setRequestFocusEnabled(false);
                FAvailableRoles.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

                jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/526.jpg"))); // NOI18N
                jLabel8.setRequestFocusEnabled(false);
                FAvailableRoles.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

                getContentPane().add(FAvailableRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 130, 380));

                FPlayerNames.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                FPlayerNames.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jTextField10.setEditable(false);
                jTextField10.setFont(new java.awt.Font("Tahoma", 1, 11));
                jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField10.setText("Player Names and AI Control");
                jTextField10.setBorder(null);
                FPlayerNames.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 170, -1));

                jTextField11.setEditable(false);
                jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField11.setText("Human Player");
                jTextField11.setBorder(null);
                jTextField11.setVerifyInputWhenFocusTarget(false);
                FPlayerNames.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, 65, -1));

                jTextField12.setEditable(false);
                jTextField12.setHorizontalAlignment(javax.swing.JTextField.LEFT);
                jTextField12.setText("AI Player");
                jTextField12.setBorder(null);
                jTextField12.setVerifyInputWhenFocusTarget(false);
                FPlayerNames.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 73, 65, -1));

                jTextField13.setEditable(false);
                jTextField13.setHorizontalAlignment(javax.swing.JTextField.LEFT);
                jTextField13.setText("AI Player");
                jTextField13.setBorder(null);
                jTextField13.setVerifyInputWhenFocusTarget(false);
                FPlayerNames.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, 65, -1));

                jTextField15.setEditable(false);
                jTextField15.setHorizontalAlignment(javax.swing.JTextField.LEFT);
                jTextField15.setText("AI Player");
                jTextField15.setBorder(null);
                jTextField15.setVerifyInputWhenFocusTarget(false);
                FPlayerNames.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 133, 65, -1));

                jTextField14.setEditable(false);
                jTextField14.setHorizontalAlignment(javax.swing.JTextField.LEFT);
                jTextField14.setText("AI Player");
                jTextField14.setBorder(null);
                jTextField14.setVerifyInputWhenFocusTarget(false);
                FPlayerNames.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 161, 65, -1));

                jTextField16.setEditable(false);
                jTextField16.setHorizontalAlignment(javax.swing.JTextField.LEFT);
                jTextField16.setText("Auto?");
                jTextField16.setBorder(null);
                jTextField16.setVerifyInputWhenFocusTarget(false);
                FPlayerNames.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 40, -1));

                jTextField1.setFont(new java.awt.Font("Tahoma", 0, 10));
                jTextField1.setText("Player1");
                FPlayerNames.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 40, 40, -1));

                jTextField2.setFont(new java.awt.Font("Tahoma", 0, 10));
                jTextField2.setText("Player2");
                FPlayerNames.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 40, -1));

                jTextField3.setFont(new java.awt.Font("Tahoma", 0, 10));
                jTextField3.setText("Player3");
                FPlayerNames.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 40, -1));

                jTextField4.setFont(new java.awt.Font("Tahoma", 0, 10));
                jTextField4.setText("Player4");
                FPlayerNames.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 40, -1));

                jTextField5.setFont(new java.awt.Font("Tahoma", 0, 10));
                jTextField5.setText("Player5");
                FPlayerNames.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 40, -1));

                jCheckBox1.setSelected(true);
                jCheckBox1.setInheritsPopupMenu(true);
                FPlayerNames.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 20, -1));

                jCheckBox2.setSelected(true);
                jCheckBox2.setInheritsPopupMenu(true);
                FPlayerNames.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

                jCheckBox3.setInheritsPopupMenu(true);
                FPlayerNames.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

                jCheckBox4.setInheritsPopupMenu(true);
                FPlayerNames.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

                getContentPane().add(FPlayerNames, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 190, 190));

                jButton1.setText("OK");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });
                getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 60, -1));

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseReleased
     NumPlayerClick(evt);
    }//GEN-LAST:event_jRadioButton1MouseReleased

    private void jRadioButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseReleased
     NumPlayerClick(evt);
    }//GEN-LAST:event_jRadioButton2MouseReleased

    private void jRadioButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton3MouseReleased
     NumPlayerClick(evt);
    }//GEN-LAST:event_jRadioButton3MouseReleased

    private void jRadioButton4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton4MouseReleased
     NumPlayerClick(evt);
    }//GEN-LAST:event_jRadioButton4MouseReleased

    private void jRadioButton5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton5MouseReleased
    //Pick Human Choice of Seat
    PRGDChoiceOfSeat = SetupChoiceSeat.values()[Utilities.getControlIdx(evt)];
    }//GEN-LAST:event_jRadioButton5MouseReleased

    private void jRadioButton6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton6MouseReleased
    //Pick Human Choice of Seat
    PRGDChoiceOfSeat = SetupChoiceSeat.values()[Utilities.getControlIdx(evt)];
    }//GEN-LAST:event_jRadioButton6MouseReleased

    private void jRadioButton7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton7MouseReleased
    //Pick Human Choice of Seat
    PRGDChoiceOfSeat = SetupChoiceSeat.values()[Utilities.getControlIdx(evt)];
    }//GEN-LAST:event_jRadioButton7MouseReleased

    private void jRadioButton8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton8MouseReleased
    //Pick Human Choice of Seat
    PRGDChoiceOfSeat = SetupChoiceSeat.values()[Utilities.getControlIdx(evt)];
    }//GEN-LAST:event_jRadioButton8MouseReleased

    private void jRadioButton9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton9MouseReleased
    //Pick Human Choice of Seat
    PRGDChoiceOfSeat = SetupChoiceSeat.values()[Utilities.getControlIdx(evt)];
    }//GEN-LAST:event_jRadioButton9MouseReleased

    private void jRadioButton10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton10MouseReleased
    //Pick Human Choice of Seat
    PRGDChoiceOfSeat = SetupChoiceSeat.values()[Utilities.getControlIdx(evt)];
    }//GEN-LAST:event_jRadioButton10MouseReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
     this.setVisible(false);
     PRPuertoRico.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     this.setVisible(false);
     PRPuertoRico.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
private void NumPlayerClick(java.awt.event.MouseEvent evt) {
//Pick Number of Players
  PRGDNumPlayers = Modules.SetupNumPlayers.values()[Utilities.getControlIdx(evt)];

  if ( PRGDNumPlayers == SNPlayersRandom )
   FChoiceofSeat.setVisible(false);
  else {
   FChoiceofSeat.setVisible(true);
   switch ( PRGDNumPlayers ) {

   case SNPlayers3:
    // What happens to Choice of Seat?

    // Only change this if Seat no longer valid
    if ( Option2[FourthSCS.ordinal()].isSelected()) {
     Option2[FourthSCS.ordinal()].setSelected(false);
     Option2[FirstSCS.ordinal()].setSelected(true);
     PRGDChoiceOfSeat = FirstSCS;
    };

    if ( Option2[FifthSCS.ordinal()].isSelected()) {
     Option2[FifthSCS.ordinal()].setSelected(false);
     Option2[FirstSCS.ordinal()].setSelected(true);
     PRGDChoiceOfSeat = FirstSCS;
    };

    // Disappear invalid seats
    Option2[FourthSCS.ordinal()].setVisible(false);
    Option2[FifthSCS.ordinal()].setVisible(false);

    //What happens to Available Roles?

    jLabel7.setVisible(false);  // ProspectorSAR1
    jLabel8.setVisible(false);  // ProspectorSAR2

    //What Happens to Player Names & AI?
    Label3[AIPlayerSPN3.ordinal()].setVisible(false);
    PlayerName[AIPlayerSPN3.ordinal()].setVisible(false);
    AIPlayer[AIPlayerSPN3.ordinal()].setVisible(false);
    Label3[AIPlayerSPN4.ordinal()].setVisible(false);
    PlayerName[AIPlayerSPN4.ordinal()].setVisible(false);
    AIPlayer[AIPlayerSPN4.ordinal()].setVisible(false);
    break;

   case SNPlayers4:
    // What happens to Choice of Seat?

    // Only change Value if Seat no longer valid
    if ( Option2[FifthSCS.ordinal()].isSelected()) {
     Option2[FifthSCS.ordinal()].setSelected(false);
     Option2[FirstSCS.ordinal()].setSelected(true);
     PRGDChoiceOfSeat = FirstSCS;
    };

    //Appear valid seat 4
    Option2[FourthSCS.ordinal()].setVisible(true);
    //Disappear invalid seat 5
    Option2[FifthSCS.ordinal()].setVisible(false);

    //What happens to Available Roles?
    jLabel7.setVisible(true);  // ProspectorSAR1
    jLabel8.setVisible(false);  // ProspectorSAR2

    //What Happens to Player Names?
    Label3[AIPlayerSPN3.ordinal()].setVisible(true);
    PlayerName[AIPlayerSPN3.ordinal()].setVisible(true);
    AIPlayer[AIPlayerSPN3.ordinal()].setVisible(true);
    Label3[AIPlayerSPN4.ordinal()].setVisible(false);
    PlayerName[AIPlayerSPN4.ordinal()].setVisible(false);
    AIPlayer[AIPlayerSPN4.ordinal()].setVisible(false);
    break;

   case SNPlayers5:
    // What happens to Choice of Seat?

    //Appear valid seats 4 & 5
    Option2[FourthSCS.ordinal()].setVisible(true);
    Option2[FifthSCS.ordinal()].setVisible(true);

    //What happens to Available Roles?
    jLabel7.setVisible(true);  // ProspectorSAR1
    jLabel8.setVisible(true);  // ProspectorSAR2

    //What Happens to Player Names?
    Label3[AIPlayerSPN3.ordinal()].setVisible(true);
    PlayerName[AIPlayerSPN3.ordinal()].setVisible(true);
    AIPlayer[AIPlayerSPN3.ordinal()].setVisible(true);
    Label3[AIPlayerSPN4.ordinal()].setVisible(true);
    PlayerName[AIPlayerSPN4.ordinal()].setVisible(true);
    AIPlayer[AIPlayerSPN4.ordinal()].setVisible(true);

   };
  };

};

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FSetup dialog = new FSetup(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel FAvailableRoles;
        private javax.swing.JPanel FChoiceofSeat;
        private javax.swing.JPanel FNumberofPlayers;
        private javax.swing.JPanel FPlayerNames;
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.ButtonGroup buttonGroup2;
        private javax.swing.JButton jButton1;
        private javax.swing.JCheckBox jCheckBox1;
        private javax.swing.JCheckBox jCheckBox2;
        private javax.swing.JCheckBox jCheckBox3;
        private javax.swing.JCheckBox jCheckBox4;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JRadioButton jRadioButton1;
        private javax.swing.JRadioButton jRadioButton10;
        private javax.swing.JRadioButton jRadioButton2;
        private javax.swing.JRadioButton jRadioButton3;
        private javax.swing.JRadioButton jRadioButton4;
        private javax.swing.JRadioButton jRadioButton5;
        private javax.swing.JRadioButton jRadioButton6;
        private javax.swing.JRadioButton jRadioButton7;
        private javax.swing.JRadioButton jRadioButton8;
        private javax.swing.JRadioButton jRadioButton9;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTextField jTextField10;
        private javax.swing.JTextField jTextField11;
        private javax.swing.JTextField jTextField12;
        private javax.swing.JTextField jTextField13;
        private javax.swing.JTextField jTextField14;
        private javax.swing.JTextField jTextField15;
        private javax.swing.JTextField jTextField16;
        private javax.swing.JTextField jTextField2;
        private javax.swing.JTextField jTextField3;
        private javax.swing.JTextField jTextField4;
        private javax.swing.JTextField jTextField5;
        private javax.swing.JTextField jTextField6;
        private javax.swing.JTextField jTextField8;
        private javax.swing.JTextField jTextField9;
        // End of variables declaration//GEN-END:variables
public javax.swing.JCheckBox AIPlayer [] = new javax.swing.JCheckBox[MaxPlayers];
public javax.swing.JTextField PlayerName [] = new javax.swing.JTextField [MaxPlayers];
private javax.swing.JRadioButton Option2[] = new javax.swing.JRadioButton [MaxPlayers+1];
private javax.swing.JTextField Label3[] = new javax.swing.JTextField[MaxPlayers];
}
